language: python

sudo: required

cache:
    - pip
    - npm

node_js:
    - "5.11.1"

python:
    - "3.6"

install:
    - ./test/install.sh
    - pip install -r test/requirements.txt

script:
    - cd test && pytest -v test.py
