language: python

sudo: required

cache:
    - pip
    - npm

env:
    - NODE_VERSION="5.11.1"

python:
    - "3.6"

before_install:
    - nvm install $NODE_VERSION

install:
    - ./test/install.sh
    - pip install -r test/requirements.txt

script:
    - cd test && pytest -v test.py
